### ISSUE TITLE
Torrent Link broken on http://directhex.github.io/

### ISSUE THREAD

**Issue by Shaggygoblin** [steamos-community/stephensons-rocket#100]
http://retro.apebox.org/StephensonsRocket93plus1.iso.torrent
broken.
going to http://retro.apebox.org, there is an .iso link: http://retro.apebox.org/SteamOSDVD.iso
That doesn't appear to be Rocket.

The Magnet Link appears to work.  Still downloading...

**Comment by sharkwouter** [comment]
93 is extremely old, though.

**Comment by directhex** [comment]
Old site nuked, w/ a redirect.

**Comment by Shaggygoblin** [comment]
"93 is extremely old, though."

I need to Dual-Boot SteamOS with Win7, and not loose my Win7.  All my searches pointed to SR93+1.
If this is indeed old/outdated, please tell me where I can find a more recent Dual-Boot-able option that supports Chipset RAID and AMD Graphics.

**Comment by sharkwouter** [comment]
http://stephensonsrocket.horse/
