### ISSUE TITLE
ERROR on Local installer message

### ISSUE THREAD

**Issue by mdeguzis** [steamos-community/stephensons-rocket#110]
Cloned the repo, ran `git checkout brewmaster` then go this kickback:

```
ERROR! Local installer and remote installer both unknown
ERROR! Please update gen.sh to support unknown SteamOSDVD.iso
```

I know you haven't made commits lately, so i'm trying to figure out what's going on.

```
https://github.com/steamos-community/stephensons-rocket
cd stephensons-rocket
./gen.sh
```

If the Valve repo updated, do you need an updated MD5/SHA?

**Comment by mdeguzis** [comment]
The MD5 should be `79deb18e5daea46d4e11cbc65a539724`. Why not always actively pull this checksum? See: PR #111

**Comment by directhex** [comment]
We need to update the installer. It's not as simple as just updating the checksum, for 2 reasons:
- Valve don't keep old versions, so we can't download one we definitely know works
- When a new ISO is released, it means there is stuff to actively change, so just updating it on its own is not enough (best-case, update debstoremove in gen.sh and the packages in pool/ to account for the updates in the new ISO)

**Comment by sharkwouter** [comment]
I'm working on updating it right now, I'll push it when I know it works.

**Comment by sharkwouter** [comment]
It has been updated to support 2.32 now.

**Comment by sharkwouter** [comment]
This is by design and will not be fixed unless Valve starts providing downloads for old ISOs in the future.
