### ISSUE TITLE
No Opengl 4.0 Support

### ISSUE THREAD

**Issue by gtguy** [steamos-community/stephensons-rocket#113]
I have an Nvidia GTX 260.  The lastest drivers for this are 340.65.   I cannot run anyting which requires Opengl 4.0 Support.  Metro Redux titles can be used to test this.  I tried to download and install 340.65 following steam forum instructions http://steamcommunity.com/groups/steamuniverse/discussions/1/540743757298243719/  but it didnt work.  Should I even be doing this?  Or are drivers supposed to update themselves?   I  wanted to try the sgfxi script to install drivers but I couldnt figure it out.   What is the easiest way to get Opengl 4.0 support?  Thanks!

**Comment by directhex** [comment]
I'm not sure what you're asking here.

Stephenson's Rocket already ships with 340.76 parallel-installed with the newer driver, and will swap to the 340 driver for all old cards going back to around the 8000 series. 340.76 supports OpenGL 4.5 - but your specific hardware may not support the specific extensions needed by a given game.

If you're messing with installers or scripts, you're doing it wrong.

**Comment by gtguy** [comment]
Thanks for the response.

**Comment by tomtomme** [comment]
no it does not:
https://en.wikipedia.org/wiki/GeForce_200_series
this is directx10 opengl 3.3 hardware only

**Comment by sharkwouter** [comment]
I'm closing this, since it is a hardware limitation.
