### ISSUE TITLE
GUI Glitch in Installer

### ISSUE THREAD

**Issue by ShiromMakkad** [steamos-community/stephensons-rocket#120]
After you click on any of the install versions, the screen starts to tear and you can't select anything after that. This means that you can not install Stephenson's Rocket.

**Comment by sharkwouter** [comment]
Could you take a picture? What hardware are you using?

This is quite odd, since the installer doesn't should use the vesa driver to draw graphics.

**Comment by ShiromMakkad** [comment]
Here: http://imgur.com/xsFOdYW

This also happens on vaporos but not on valve's steamos. The reason I can't use steamos is because I have had a lot of issues with it ranging from blank screens, corrupting other non steam partition,  and even requiring me to delete all other OS's off my computer and reinstall them.

**Comment by ShiromMakkad** [comment]
I was thinking, maybe you could give me an older version of Stephenson's rocket and see if that works. I looked online and couldn't find any downloads for older versions.

**Comment by sharkwouter** [comment]
This may be because stephenson's rocket is based on an older version of SteamOS. Are you using a very new cpu?

**Comment by ShiromMakkad** [comment]
The computer is a sony vaio customizable computer that's about 3 yrs old. 
- core i5 3210m
- 6gb of ram
- amd radeon hd 7500m/7600m
- UEFI mobo

**Comment by directhex** [comment]
Has a difference emerged in kernel params? (i.e. grub.cfg/isolinux config files)? Looks related to modesetting

**Comment by ShiromMakkad** [comment]
I don't know how to check that. Right now I am at school, and I won't be home for 9 hours. I can try and help you as much as I can, but I don't have access to my computer.

**Comment by ShiromMakkad** [comment]
You guys there?
