### ISSUE TITLE
Can't run post_install.sh

### ISSUE THREAD

**Issue by JigglypuffPC** [steamos-community/stephensons-rocket#24]
So I choose the Power User option and everything goes fine. I partition my harddisk for SteamOS, everything all good. It installs the base system and grub just fine, but when it goes to the step "finishing installation" it gives me an error: Error executing script "/cdrom/post_install.sh". It then finishes the rest of the steps and tells me to take out my install CD, which I do that. I then boot into SteamOS and i can only log in to the user "desktop" and not the user "steam". This is because post_install.sh is the script that creates the "steam" user. Can anyone help me with this? I'm using UEFI if that helps.

**Comment by ctmarc** [comment]
If you get a error 127 for `/bin/sh` try `bash` instead of `sh`. On my installation the symlink `sh` is not available at this stage.
