### ISSUE TITLE
Stuck on steamos logo issue

### ISSUE THREAD

**Issue by Redn2000** [steamos-community/stephensons-rocket#32]
Hello I haven't been able to get it to boot past the steamos logo after it says setting up drivers. I followed your instructions for dual boot. However I did accidentally jump into the boot and had to restart my computer before doing the grab partition part. And then did the grab partition for it. However after all this I had to remove the partitions created and moved back to windows 8. Any suggestions?

**Comment by sharkwouter** [comment]
This issue is really old and no updates have been provided. Neither has anyone else confirmed this issue. I'll close it for now, if you see this issue popping up again please reopen it.

**Comment by GuestSneezeOSDev** [comment]
@sharkwouter  What GPU Does Your Computer Have The version You Are Using Is SteamOS 2 Which Does Not Support Nvidia GPU's

**Comment by sharkwouter** [comment]
@GuestSneezeOSDev I'm developer behind VaporOS and was a maintainer for Stephenson's Rocket. Both have been dicontinued now and I've personally switched to ChimeraOS, to which I did some contributions as well. I don't need support, thanks for offering, though.
