### ISSUE TITLE
switch wget with lftp

### ISSUE THREAD

**Issue by tommyla** [steamos-community/stephensons-rocket#34]
well, downloading the iso off valve takes it sweet time with wget, would be a good idea to use lftp instead it as it can load more connections and download it at  warp speed :100:

apt-get install lftp :monkey: 

example
lftp -e 'pget -n 8  http://repo.steampowered.com/download/SteamOSDVD.iso'

lftp: 12.05M/s :+1:  wget  612KB/s :-1: 

lftp is pretty useful for other things like mirroring whole directories from one server to another, think backups :+1: 
http://www.cyberciti.biz/faq/lftp-mirror-example/

lftp can be found here on github or at developer site
https://github.com/lavv17/lftp
http://lftp.yar.ru

**Comment by sharkwouter** [comment]
lftp should be available in both Debian and Ubuntu: https://packages.debian.org/jessie/lftp

**Comment by sharkwouter** [comment]
I just created a pull request with lftp as downloader: https://github.com/steamos-community/stephensons-rocket/pull/115

I'll leave it up to @directhex to actually pull it in.
