### ISSUE TITLE
SteamOS dont launch a 2nd time

### ISSUE THREAD

**Issue by Pelluzi** [steamos-community/stephensons-rocket#43]
steamos when my first start after installation it works for 1 minute and then restarts ... after that when you start it just sits with a black screen, sometimes it flashes an icon mouse in center of screen ... I have a xfx video card series r7700......ye old steamo and stemos i have the same problems....

**Comment by sharkwouter** [comment]
This is no longer a problem in the current version of Stephenson's Rocket.
