### ISSUE TITLE
Drive not bootable after automated install

### ISSUE THREAD

**Issue by menotti-twitter** [steamos-community/stephensons-rocket#44]
Choosing the automated install option, the whole thing goes through seemingly successfully. On first reboot, my machine doesn't find a bootable drive other than my usb stick. It's as if the hard disk isn't bootable after install. The vanilla steamos seems to work OK in this regard.

**Comment by mdeguzis** [comment]
Sounds like you did a UEFI install, then didn't set secure boot in your motherboard settings. I for one, have a dual-boot "amazing" Gigabyte board that has BIOS and EFI. I know I had to turn on the Windows 7/8 features (joy), and for CSM, select "never" and installed again. What is your hardware?

**Comment by sharkwouter** [comment]
I'm closing this, because this issue hasn't been updated by the OP for a very long time.
