### ISSUE TITLE
Grub Install Failure to /dev/sda

### ISSUE THREAD

**Issue by bwrigh16** [steamos-community/stephensons-rocket#92]
Not sure if this is a good spot to put this or not. But grub fails installing to /dev/sda. /dev/sda doesnt seem to exist.

**Comment by sharkwouter** [comment]
I suspect this issue is not present in Stephenson's Rocket, but is in VaporOS and Valve's installer.

**Comment by AndrewSav** [comment]
I have the same issue. The box has no hard drive and two usb external drives. One with stephenson's rocket and the other is empty. I'm suspecting that /dev/sda is the first usb drive and the second one is in fact /dev/sdb. This link talks about a similar issue in ubuntu http://askubuntu.com/questions/459620/unable-to-install-grub-in-dev-sda-when-installing-grub this is not debian but close enough. In ubuntu it's possible to actually select path /dev/sdb from the installer UI. I wonder if it's possible with stephenson's rocket.

Also if anyone know if there is any tech forum or anything where this question has a chance to be answered please let me know.

**Comment by directhex** [comment]
Okay, this is a side-effect of the automatic installer's best efforts. You'll need to check out from git and make your own image as a fix.

If you delete [this line](https://github.com/steamos-community/stephensons-rocket/blob/master/default.preseed#L154), and run a custom install, you should be able to control where to install GRUB. As-is, the line scans fixed disks, and forces the first one as the install location, skipping the dialog box.

**Comment by AndrewSav** [comment]
Worked for me. Thanks.

**Comment by sharkwouter** [comment]
Should be fixed in the current version.
