### ISSUE TITLE
cannot get root access.

### ISSUE THREAD

**Issue by Shadow125** [steamos-community/stephensons-rocket#93]
I am unable to gain root access to the Steam OS desktop account. I require this so I can install the firmware for my wireless netwok card. I tried following the directions on Steams FAQ's but they claim no password is set. When I try to set the password as per their instructions I cannot because there is an existing password. So I assume one was set in your build. Is it possible to obtain that password or am I doing something wrong?

**Comment by sharkwouter** [comment]
You are asked to set a password when you first open the desktop on vaporos.

**Comment by maritz** [comment]
I'm having the same issue. I was not asked for a password during install and "desktop" does not work.

**Comment by directhex** [comment]
How did you create your installation media?

**Comment by maritz** [comment]
With unetbootin. Everything else works really well, and I've even played some CS:GO on it to test it. Missing root access is the only thing that doesn't work so far. Is that really something that could be caused by using the wrong program to create the bootable USB install?

**Comment by directhex** [comment]
Unetbootin deliberately breaks all debian-installer based images.

EVERY other imaging tool, including "dd", will work.

**Comment by maritz** [comment]
Okay, now I used Win32 Disk Imager and completely reinstalled and still have the same issue.

After the first boot it put me on the desktop so I could enter my WIFI data, then it updated steam and all that, rebooted again, went to steam mode. I logged in with my steam account, enabled desktop access in the settings, went to the desktop and got no prompt at all.

**Comment by directhex** [comment]
So can you switch to the desktop user now? If so, use "passwd" to set  a password, then "sudo -i" to get a root prompt

**Comment by directhex** [comment]
https://github.com/ValveSoftware/SteamOS/issues/311

**Comment by maritz** [comment]
Okay, passwd worked. For some reason I assumed that a password was set and I'd need to know it.

BTW: Everything looked exactly the same with unetbootin as with win32 disk imager. I don't think there is actually a difference for me.

**Comment by directhex** [comment]
A password is set during installation, because the installer requires it to proceed, then gets wiped out by the post-install script
