### ISSUE TITLE
Website permalink broken

### ISSUE THREAD

**Issue by DerfOh** [steamos-community/stephensons-rocket#99]
I get the following error when trying to download the lates ISO from http://repo.steampowered.com/download/SteamOSDVD.iso

<blockquote>
Error 503 Service Unavailable

Service Unavailable

Guru Meditation:

XID: 1166022183

Varnish cache server6
</blockquote>

**Comment by DerfOh** [comment]
This would be the link to the Steam OS iso to clarify

**Comment by directhex** [comment]
Valve's broken CDN is outside my control. That's still the right URL.
